### ISSUE TITLE
[solved via workaround] pywintypes38.dll can't be found (python3.8 on windows 7 ultimate)

### ISSUE THREAD

**Issue by targodan** [fkie-cad/RoAMer#5]
### Problem

When running `compile.bat`, I get the following warning:

```
4437 WARNING: lib not found: pywintypes38.dll dependency of C:\program files\python38\lib\site-packages\win32\win32evtlog.pyd
4453 WARNING: lib not found: pywintypes38.dll dependency of C:\program files\python38\lib\site-packages\win32\win32api.pyd
4468 WARNING: lib not found: pywintypes38.dll dependency of C:\program files\python38\lib\site-packages\win32\win32process.pyd
```

The compilation completes, but when running `main.exe` it errors with this message:

```
[backtrace omitted since can't copy-paste from my vm]
ImportError: DLL load failed while importing win32process: The specified module could not be found.
[544] Failed to execute script main
```

### Solution/Workaround

I found the missing `pywintypes38.dll` in `C:\progam files\python38\lib\site-packages\pywin32_system32\pywintypes38.dll` and copied it to `C:\windows\system32`, then I ran `compile.bat` again to be on the safe side and it worked. Worked, meaning no warning when running compile and executing the main.exe does not result in a crash.

### How to reproduce

I'm running windows 7 x64 Ultimate in a libvirt/qemu VM, installed latest python 3.8 (for all users, i. e. in `C:\program files\...`) and ran this command as admin to fulfil the dependencies:

```
pip install pyinstaller pywin32
```

Not sure if it's a bug in pip, the pywin32 package or a combination of these with win7 ultimate. Mentioning this workaround in the README would be sufficient IMO as I'm not sure this *can* be fixed from within this project.

(Note, this also happened on my win10 eval vm, but I did not report it then, because I didn't take notes when fixing it.)

**Comment by UrmelAusDemEis** [comment]
This is (as mentioned) a direct result of issue #6 
We can track pyinstaller progress in the other issue :)
